# .github/workflows/ci.yml

name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps: # clonar el repo a un entorno de github actions
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Go # setear go con su v
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.17

    - name: Run Tests # correr los tests
      run: go test -v ./...
